/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DidRegistry } from "./DidRegistry";
export * as factories from "./factories";
export { DidRegistry__factory } from "./factories/DidRegistry__factory";
