/**
 * This file is part of the DocuSign project.
 */

type Env = {
  VITE_NODE_ENV: string;
  VITE_CHAIN_ID: string;
  VITE_API_BASE_URL: string;
  VITE_RPC_URL: string;
  VITE_WALLETCONNECT_PROJECT_ID?: string;
  VITE_DID_REGISTRY_CONTRACT_ADDRESS?: string;
  VITE_DID_ISSUER_CONTRACT_ADDRESS?: string;
  VITE_DID_VERIFIER_CONTRACT_ADDRESS?: string;
  VITE_DOCU_VAULT_CONTRACT_ADDRESS?: string;
  VITE_DID_AUTH_CONTRACT_ADDRESS?: string;
  VITE_VERIFIER_FACTORY_CONTRACT_ADDRESS?: string;
  VITE_AGE_VERIFIER_CONTRACT_ADDRESS?: string;
  VITE_HASH_VERIFIER_CONTRACT_ADDRESS?: string;
  VITE_SEPOLIA_CHAIN_ID?: string;
  VITE_SEPOLIA_API_BASE_URL?: string;
  VITE_SEPOLIA_RPC_URL?: string;
  VITE_COOKIE_SECRET?: string;
};
const localEnv: Env = {
  VITE_NODE_ENV: import.meta.env.VITE_NODE_ENV || 'development',
  VITE_CHAIN_ID: import.meta.env.VITE_CHAIN_ID || '31337',
  VITE_API_BASE_URL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/api/v1',
  VITE_RPC_URL: import.meta.env.VITE_RPC_URL || 'http://127.0.0.1:8545',
  VITE_WALLETCONNECT_PROJECT_ID: import.meta.env.VITE_WALLETCONNECT_PROJECT_ID!,
  VITE_DID_REGISTRY_CONTRACT_ADDRESS: import.meta.env.VITE_DID_REGISTRY_CONTRACT_ADDRESS,
  VITE_DID_ISSUER_CONTRACT_ADDRESS: import.meta.env.VITE_DID_ISSUER_CONTRACT_ADDRESS,
  VITE_DID_VERIFIER_CONTRACT_ADDRESS: import.meta.env.VITE_DID_VERIFIER_CONTRACT_ADDRESS,
  VITE_DOCU_VAULT_CONTRACT_ADDRESS: import.meta.env.VITE_DOCU_VAULT_CONTRACT_ADDRESS,
  VITE_DID_AUTH_CONTRACT_ADDRESS: import.meta.env.VITE_DID_AUTH_CONTRACT_ADDRESS,
  VITE_VERIFIER_FACTORY_CONTRACT_ADDRESS: import.meta.env.VITE_VERIFIER_FACTORY_CONTRACT_ADDRESS,
  VITE_AGE_VERIFIER_CONTRACT_ADDRESS: import.meta.env.VITE_AGE_VERIFIER_CONTRACT_ADDRESS,
  VITE_HASH_VERIFIER_CONTRACT_ADDRESS: import.meta.env.VITE_HASH_VERIFIER_CONTRACT_ADDRESS,
  VITE_COOKIE_SECRET: import.meta.env.VITE_COOKIE_SECRET || 'default_cookie_secret',
};

const sepoliaEnv: Env = {
  VITE_NODE_ENV: import.meta.env.VITE_NODE_ENV || 'development',
  VITE_CHAIN_ID: import.meta.env.VITE_SEPOLIA_CHAIN_ID || '11155111',
  VITE_API_BASE_URL: import.meta.env.VITE_SEPOLIA_API_BASE_URL || 'http://localhost:5000/api/v1',
  VITE_RPC_URL: import.meta.env.VITE_SEPOLIA_RPC_URL!,
  VITE_DID_REGISTRY_CONTRACT_ADDRESS: import.meta.env.VITE_SEPOLIA_DID_REGISTRY_CONTRACT_ADDRESS,
  VITE_DID_ISSUER_CONTRACT_ADDRESS: import.meta.env.VITE_SEPOLIA_DID_ISSUER_CONTRACT_ADDRESS,
  VITE_DID_VERIFIER_CONTRACT_ADDRESS: import.meta.env.VITE_SEPOLIA_DID_VERIFIER_CONTRACT_ADDRESS,
  VITE_DOCU_VAULT_CONTRACT_ADDRESS: import.meta.env.VITE_SEPOLIA_DOCU_VAULT_CONTRACT_ADDRESS,
  VITE_DID_AUTH_CONTRACT_ADDRESS: import.meta.env.VITE_SEPOLIA_DID_AUTH_CONTRACT_ADDRESS,
  VITE_VERIFIER_FACTORY_CONTRACT_ADDRESS: import.meta.env.VITE_SEPOLIA_VERIFIER_FACTORY_CONTRACT_ADDRESS,
  VITE_AGE_VERIFIER_CONTRACT_ADDRESS: import.meta.env.VITE_SEPOLIA_AGE_VERIFIER_CONTRACT_ADDRESS,
  VITE_HASH_VERIFIER_CONTRACT_ADDRESS: import.meta.env.VITE_SEPOLIA_HASH_VERIFIER_CONTRACT_ADDRESS,
  VITE_WALLETCONNECT_PROJECT_ID: import.meta.env.VITE_SEPOLIA_WALLETCONNECT_PROJECT_ID,
  VITE_COOKIE_SECRET: import.meta.env.VITE_SEPOLIA_COOKIE_SECRET || 'default_sepolia_cookie_secret',
};

export const isProd = import.meta.env.NODE_ENV === 'production';

export const env = isProd ? sepoliaEnv : localEnv;
