services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: docuvault-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DocuVault_P@ssw0rd
      - MSSQL_PID=Express
    ports:
      - '1433:1433'
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "DocuVault_P@ssw0rd" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqlserver-data:
    driver: local
