name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - feature/contract-deployment
      - deploy/static-web-app
    paths:
      - 'apps/web/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'apps/web/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Web App
        run: pnpm build --filter=docu-vault-web
        env:
          VITE_NODE_ENV: 'production'
          VITE_API_BASE_URL: 'https://docu-vault-api.azurewebsites.net/api/v1'
          VITE_SEPOLIA_CHAIN_ID: '11155111'
          VITE_COOKIE_SECRET: ${{ secrets.VITE_COOKIE_SECRET }}
          VITE_SEPOLIA_RPC_URL: ${{ secrets.VITE_SEPOLIA_RPC_URL }}
          VITE_SEPOLIA_DOCU_VAULT_CONTRACT_ADDRESS: '0x9F2e9D5029FE75c0112b64974f98784402efb7bB'
          VITE_SEPOLIA_DID_REGISTRY_CONTRACT_ADDRESS: '0xAe410e4483ce22Db8A7C6a815b20Bce2AcB7C78B'
          VITE_SEPOLIA_DID_AUTH_CONTRACT_ADDRESS: '0x0b7F3f1436A47e33f953521bBFD2887A90b2FA60'
          VITE_SEPOLIA_DID_ISSUER_CONTRACT_ADDRESS: '0xcE9719191DeB7FE3221b1966A75C9750b07C7fcC'
          VITE_SEPOLIA_DID_VERIFIER_CONTRACT_ADDRESS: '0x83A0D19E46f134A757B11107F781Cf2b83755274'
          VITE_WALLETCONNECT_PROJECT_ID: ${{ secrets.VITE_WALLETCONNECT_PROJECT_ID }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: upload-dist

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'upload-dist'
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'close'
